use_frameworks!

target 'TPInjector_Example' do
  pod 'TPInjector', :path => '../'

  target 'TPInjector_Tests' do
    inherit! :search_paths
    pod 'TPInjector', :path => '../'

    pod 'Nimble', '~> 7.0.2'
  end
end
