use_frameworks!

target 'TPInjector_Example' do
  pod 'TPInjector', :path => '../'

  target 'TPInjector_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
